# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 08:04
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='商品详情'),
        ),
    ]
